version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: frontend_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - frontend_db_data:/var/lib/mysql
    restart: always
    networks:
      - frontend_network

  wordpress:
    image: wordpress:latest
    container_name: frontend_wordpress
    ports:
      - "30010:80"
    environment:
      DB_HOST: mysql
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - frontend_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: frontend_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "30011:80"
    depends_on:
      - db
    restart: always
    networks:
      - frontend_network

networks:
  frontend_network:
    name: frontend_network
    driver: bridge

volumes:
  frontend_db_data:
  wordpress_data: